version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    environment:
      CC_TEST_REPORTER_ID: 12d3d4baa24ff10c60448b1e02f07218f6a8076f4c2c3af91045e1fb7df14a96
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          command: pytest
          name: Test
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter


workflows:
  main:
    jobs:
      - build-and-test
